export const coachName: Record<string, string> = {
    'Pep Guardiola': '펩 과르디올라',
    'Arne Slot': '아르네 슬롯',
    "Mikel Arteta": "미켈 아르테타",
    "Unai Emery": "우나이 에메리",
    "Enzo Maresca": "엔초 마레스카",
    "Fabian Hürzeler": "파비안 휘르첼러",
    "Nuno Espírito Santo": "누누 산투",
    "Ange Postecoglou": "엔지 포스테코글루",
    "Thomas Frank": "토마스 프랑크",
    "Marco Silva": "마르쿠 실바",
    "Iraola": "안도니 이라올라",
    "Eddie Howe": "에디 하우",
    "Julen Lopetegui": "훌렌 로페테기",
    "Ruud van Nistelrooy": "뤼트 반니스텔로이",
    "Steve Cooper": "스티브 쿠퍼",
    "Sean Dyche": "션 다이치",
    "Oliver Glasner": "올리버 글라스너",
    "Kieran McKenna": "키어런 맥케나",
    "Gary O'Neil": "게리 오닐",
    "Russell Martin": "러셀 마틴",
    "Vincent Kompany": "뱅상 콤파니",
    "Marco Rose": "마르코 로제",
    "Xabi Alonso": "샤비 알론소",
    "Bo Svensson": "보 스벤손",
    "Julian Schuster": "율리안 슈스터",
    "Dino Toppmöller": "디노 토프묄러",
    "Nuri Şahin": "누리 샤힌",
    "Sebastian Hoeneß": "제바스티안 회네스",
    "Ole Werner": "올레 베르너",
    "Frank Schmidt": "프랑크 슈미트",
    "Gerardo Seoane": "헤라르도 세오아네",
    "Jess Thorup": "예스 토루프",
    "Bo Henriksen": "보 헨릭센",
    "Ralph Hasenhüttl": "랄프 하젠휘틀",
    "Pellegrino Matarazzo": "펠레그리노 마타라초",
    "Alexander Blessin": "알렉산더 블레신",
    "Marcel Rapp": "마르셀 라프",
    "Markus Feldhoff": "마르쿠스 펠드호프",
    "Hansi Flick": "한지 플릭",
    "Carlo Ancelotti": "카를로 안첼로티",
    "Marcelino": "마르셀리노",
    "Diego Simeone": "디에고 시메오네",
    "Ernesto Valverde": "에르네스토 발베르데",
    "Manuel Pellegrini": "마누엘 펠레그리니",
    "Jagoba Arrasate": "하고바 아라사테",
    "Moreno": "모레노",
    "Iñigo Pérez": "이니고 페레스",
    "Garcia Pimienta": "가르시아 피미엔타",
    "Claudio": "클라우디오",
    "Imanol Alguacil": "이마놀 알과실",
    "Michel": "미첼",
    "Borja Jiménez": "보르하 히메네스",
    "Pepe Bordalás": "호세 보르달라스",
    "Luís García": "루이스 가르시아",
    "Manolo González": "마놀로 곤살레스",
    "Diego Martínez": "디에고 마르티네스",
    "Paulo Pezzolano": "파울로 페촐라노",
    "Rubén Baraja": "루벤 바라하",
    "Antonio Conte": "안토니오 콘테",
    "Simone Inzaghi": "시모네 인자기",
    "Thiago Motta": "티아고 모타",
    "Raffaele Palladino": "라파엘레 팔라디노",
    "Gian Piero Gasperini": "지안 피에로 가스페리니",
    "Marco Baroni": "마르코 바로니",
    "Kosta Runjaić": "코스타 루냐이치",
    "Paulo Fonseca": "파울로 폰세카",
    "Paolo Vanoli": "파올로 바놀리",
    "Vincenzo Italiano": "빈센초 이탈리아노",
    "Roberto D'Aversa": "로베르토 다베르사",
    "Ivan Juric": "이반 유리치",
    "Fàbregas": "세스크 파브레가스",
    "Paolo Zanetti": "파올로 자네티",
    "Davide Nicola": "다비데 니콜라",
    "Alessandro Nesta": "알레산드로 네스타",
    "Fabio Pecchia": "파비오 페키아",
    "Luca Gotti": "루카 고티",
    "Alberto Gilardino": "알베르토 질라르디노",
    "Eusebio Di Francesco": "에우제비오 디프란체스코",
    "Luis Enrique": "루이스 엔리케",
    "Adi Hütter": "아디 휘터",
    "Roberto De Zerbi": "로베르토 데 제르비",
    "Bruno Génésio": "브루노 제네시오",
    "Will Still": "윌 스틸",
    "Pierre Sage": "피에르 사즈",
    "Luka Elsner": "루카 엘스네르",
    "Franck Haise": "프랑크 에스",
    "Liam Rosenior": "리암 로세니어",
    "Eric Roy": "에릭 로이",
    "Julien Stéphan": "쥘리앙 스테판",
    "Antoine Kombouare": "앙투안 콩부아레",
    "Christophe Pélissier": "크리스토프 펠리시에",
    "Carles Martínez": "카를레스 마르티네스",
    "Alexandre Dujeux": "알렉상드르 뒤주",
    "Olivier Dall'Oglio": "올리비에 달롤리오",
    "Didier Digard": "디디에 디가르",
    "Jean-Louis Gasset": "장루이 가세",
    "Ruben Amorim": "후벵 아모림",
    "Bruno Lage": "브루노 라즈",
    "Brian Priske": "브리안 프리스케",
    "Brendan Rodgers": "브렌던 로저스",
    "Lars Friis": "라스 프리스",
    "Nenad Bjelica": "네나드 비엘리차",
    "Nicky Hayen": "니키 하옌",
    "Peter Bosz": "페터르 보츠",
    "Marino Pusic": "마리노 푸시치",
    "Christian Ilzer": "크리스티안 일처",
    "Vladan Milojević": "블라단 밀로예비치",
    "Joël Magnin": "조엘 마냉",
    "Pepijn Lijnders": "펩 레인더스",
    "Vladimir Weiss": "블라디미르 바이스"
}