type TranslatedKoreanVer = Record<string, string>

export const plTeamsName: TranslatedKoreanVer = {
    "Manchester City FC": "맨체스터 시티",
    "West Ham United FC": "웨스트햄 유나이티드",
    "Tottenham Hotspur FC": "토트넘 홋스퍼",
    "Liverpool FC": "리버풀",
    "Arsenal FC": "아스날",
    "Brighton & Hove Albion FC": "브라이튼 앤 호브 알비온",
    "Aston Villa FC": "아스톤 빌라",
    "Manchester United FC": "맨체스터 유나이티드",
    "Brentford FC": "브렌트포드",
    "Chelsea FC": "첼시",
    "Crystal Palace FC": "크리스탈 팰리스",
    "Fulham FC": "풀럼",
    "Newcastle United FC": "뉴캐슬 유나이티드",
    "Nottingham Forest FC": "노팅엄 포레스트",
    "Wolverhampton Wanderers FC": "울버햄튼 원더러스",
    "AFC Bournemouth": "본머스",
    "Ipswich Town FC": "입스위치 타운",
    "Leicester City FC": "레스터 시티",
    "Southampton FC": "사우스햄튼",
    "Everton FC": "에버튼"
}

export const plPlayerName: TranslatedKoreanVer = {
    "Erling Haaland": "엘링 홀란",
    "Mohamed Salah": "모하메드 살라",
    "Cole Palmer": "콜 파머",
    "Bryan Mbeumo": "브라이언 음뵈모",
    "Danny Welbeck": "대니 웰벡",
    "Nicolas Jackson": "니콜라스 잭슨",
    "Luis Díaz": "루이스 디아스",
    "Ollie Watkins": "올리 왓킨스",
    "Liam Delap": "리암 델랍",
    "Chris Wood": "크리스 우드",
}

export const nationality: TranslatedKoreanVer = {
    "Norway": "노르웨이",
    "Nigeria": "나이지리아",
    "England": "잉글랜드",
    "Cameroon": "카메룬",
    "Spain": "스페인",
    "France": "프랑스",
    "Sweden": "스웨덴",
    "Denmark": "덴마크",
    "Germany": "독일",
    "Guinea": "기니",
    "Belgium": "벨기에",
    "Czech Republic": "체코",
    "DR Congo": "콩고민주공화국",
    "Brazil": "브라질",
    "Netherlands": "네덜란드",
    "Venezuela": "베네수엘라",
    "Uruguay": "우루과이",
    "Argentina": "아르헨티나",
    "Morocco": "모로코",
    "Italy": "이탈리아",
    "Serbia": "세르비아",
    "USA": "미국",
    "Egypt": "이집트",
    "Jordan": "요르단",
    "Japan": "일본",
    "Portugal": "포르투갈",
    "Colombia": "콜롬비아",
    "New Zealand": "뉴질랜드",
    "Senegal": "세네갈",
    "Bosnia-Herzegovina": "보스니아-헤르체고비나",
    "Croatia": "크로아티아",
    "Poland": "폴란드",
    "Georgia": "조지아",
    "Romania": "루마니아",
    "Canada": "캐나다",
    "South Korea": "대한민국",
    "Slovenia": "슬로베니아",
    "Turkey": "튀르키예"
}

export const bundesTeamName: TranslatedKoreanVer = {
    "1. FC Union Berlin": "우니온 베를린",
    "FC Bayern München": "바이에른 뮌헨",
    "Bayer 04 Leverkusen": "바이엘 04 레버쿠젠",
    "VfL Wolfsburg": "볼프스부르크",
    "SC Freiburg": "프라이부르크",
    "Borussia Dortmund": "보루시아 도르트문트",
    "Eintracht Frankfurt": "프랑크푸르트",
    "RB Leipzig": "RB 라이프치히",
    "VfB Stuttgart": "슈투트가르트",
    "TSG 1899 Hoffenheim": "호펜하임",
    "FC Augsburg": "아우크스부르크",
    "Borussia Mönchengladbach": "보루시아 묀헨글라트바흐",
    "1. FSV Mainz 05": "FSV 마인츠 05",
    "VfL Bochum 1848": "VFL 보훔",
    "Holstein Kiel": "홀슈타인 킬",
    "1. FC Heidenheim 1846": "하이덴하임",
    "FC St. Pauli 1910": "FC 장크트파울리",
    "SV Werder Bremen": "베르더 브레멘",
}

export const bundesPlayerName: TranslatedKoreanVer = {
    "Omar Marmoush": "오마르 마르무시",
    "Tim Kleindienst": "팀 클라인딘스트",
    "Harry Kane": "해리 케인",
    "Andrej Kramarić": "안드레이 크라마리치",
    "Ermedin Demirovic": "에르메딘 데미로비치",
    "Jonathan Burkardt": "요나탄 부르카르트",
    "Victor Boniface": "빅터 보니페이스",
    "Loïs Openda": "로이스 오펜다",
    "Deniz Undav": "데니스 운다브",
    "Michael Olise": "마이클 올리세"
}

export const laligaTeamName: TranslatedKoreanVer = {
    "Real Madrid CF": "레알 마드리드",
    "Club Atlético de Madrid": "아틀레티코 마드리드",
    "Girona FC": "지로나",
    "FC Barcelona": "FC 바르셀로나",
    "Athletic Club": "아틀레틱 클럽 빌바오",
    "CA Osasuna": "오사수나",
    "Valencia CF": "발렌시아 CF",
    "Rayo Vallecano de Madrid": "라요 바예카노",
    "Real Betis Balompié": "레알 베티스",
    "Real Valladolid CF": "레알 바야돌리드",
    "Getafe CF": "헤타페",
    "Real Sociedad de Fútbol": "레알 소시에다드",
    "Villarreal CF": "비야레알",
    "Deportivo Alavés": "데포르티보 알라베스",
    "RCD Espanyol de Barcelona": "RCD 에스파뇰",
    "UD Las Palmas": "UD 라스팔마스",
    "RCD Mallorca": "RCD 마요르카",
    "RC Celta de Vigo": "셀타 비고",
    "CD Leganés": "CD 레가네스",
    "Sevilla FC": "세비야"
}

export const laligaPlayerName: TranslatedKoreanVer = {
    "Robert Lewandowski": "로베르트 레반도프스키",
    "Ayoze Pérez": "아요세 페레스",
    "Kylian Mbappé": "킬리안 음바페",
    "Vinicius Junior": "비니시우스 주니어",
    "Raphinha": "하피냐",
    "Giovani Lo Celso": "지오바니 로 셀소",
    "Oihan Sancet": "오이안 산세트",
    "Ante Budimir": "안테 부디미르",
    "Lamine Yamal": "라민 야말",
    "Dodi Lukebakio": "도디 루케바키오"
}

export const serieTeamName: TranslatedKoreanVer = {
    "AC Milan": "AC 밀란",
    "SSC Napoli": "SSC 나폴리",
    "FC Internazionale Milano": "인터 밀란",
    "Hellas Verona FC": "엘라스 베로나",
    "ACF Fiorentina": "피오렌티나",
    "Juventus FC": "유벤투스",
    "US Lecce": "US 레체",
    "Atalanta BC": "아탈란타",
    "AC Monza": "AC 몬차",
    "Venezia FC": "베네치아",
    "Genoa CFC": "제노아",
    "Como 1907": "코모",
    "AS Roma": "AS 로마",
    "Bologna FC 1909": "볼로냐",
    "Cagliari Calcio": "칼리아리 칼초",
    "Torino FC": "토리노",
    "Udinese Calcio": "우디세네 칼초",
    "SS Lazio": "SS 라치오",
    "Empoli FC": "엠폴리",
    "Parma Calcio 1913": "파르마 칼초"
}

export const seriePlayerName: TranslatedKoreanVer = {
    "Mateo Retegui": "마테오 레테기",
    "Marcus Thuram-Ulien": "마르쿠스 튀람",
    "Khvicha Kvaratskhelia": "흐비차 크바라츠헬리아",
    "Patrick Cutrone": "파트리크 쿠트로네",
    "Dennis Man": "데니스 만",
    "Duván Zapata": "두반 사파타",
    "Daniel Mosquera": "다니엘 모스케라",
    "Dušan Vlahović": "두샨 블라호비치",
    "Christian Pulisic": "크리스천 풀리식",
    "Valentín Castellanos": "발렌틴 카스테야노스",
    "Dany Mota Carvalho": "다니 모타"
}

export const leagueTeamName: TranslatedKoreanVer = {
    "AS Monaco FC": "AS 모나코",
    "Olympique de Marseille": "올림피크 마르세유",
    "Stade de Reims": "스타드 드 랭스",
    "Stade Brestois 29": "스타드 브레스투아",
    "RC Strasbourg Alsace": "RC 스트라스부르",
    "Stade Rennais FC 1901": "스타드 렌",
    "Angers SCO": "앙제 OSC",
    "Paris Saint-Germain FC": "파리 생제르맹",
    "Montpellier HSC": "몽펠리에 HSC",
    "Lille OSC": "OSC 릴",
    "Toulouse FC": "툴루즈",
    "AS Saint-Étienne": "AS 생테티엔",
    "OGC Nice": "OGC 니스",
    "Le Havre AC": "르아브르",
    "FC Nantes": "FC 낭트",
    "Racing Club de Lens": "RC 랑스",
    "Olympique Lyonnais": "올림피크 리옹",
    "AJ Auxerre": "AJ 오세르"
}

export const leaguePlayerName: TranslatedKoreanVer = {
    "Bradley Barcola": "브래들리 바르콜라",
    "Mason Greenwood": "메이슨 그린우드",
    "Jonathan David": "조너선 데이비드",
    "Keito Nakamura": "나카무라 케이토",
    "Kang-in Lee": "이강인",
    "Ousmane Dembélé": "우스만 뎀벨레",
    "Luis Henrique": "루이스 엔리케",
    "Evann Guessand": "에반 게상",
    "Andrey Santos": "안드레이 산투스",
    "Emanuel Emegha": "엠마누엘 에메가"
}

export const championsTeamName: TranslatedKoreanVer = {
    'Aston Villa FC': "아스톤 빌라",
    'Liverpool FC': '리버풀',
    'Manchester City FC': '맨체스터 시티',
    'AS Monaco FC': 'AS 모나코',
    'Stade Brestois 29': '스타드 브레스투아',
    'Bayer 04 Leverkusen': '바이엘 04 레버쿠젠',
    'FC Internazionale Milano': '인터 밀란',
    'Sporting Clube de Portugal': '스포르팅',
    'Arsenal FC': '아스날',
    'FC Barcelona': '바르셀로나',
    'Borussia Dortmund': '보루시아 도르트문트',
    'Real Madrid CF': '레알 마드리드',
    'Sport Lisboa e Benfica': 'SL 벤피카',
    'Juventus FC': '유벤투스',
    'Lille OSC': 'OSC 릴',
    'Feyenoord Rotterdam': '페예노르트',
    'Atalanta BC': '아탈란타',
    'VfB Stuttgart': '슈투트가르트',
    'Paris Saint-Germain FC': '파리 생제르맹',
    'Celtic FC': '셀틱',
    'AC Sparta Praha': '스파르타 프라하',
    'GNK Dinamo Zagreb': '디나모 자그레브',
    'FC Bayern München': '바이에른 뮌헨',
    'Girona FC': '지로나',
    'AC Milan': 'AC 밀란',
    'Club Brugge KV': '브뤼헤',
    'Club Atlético de Madrid': '아틀레티코 마드리드',
    'PSV': 'PSV 에인트호번',
    'Bologna FC 1909': '볼로냐',
    'FK Shakhtar Donetsk': '샤흐타르 도네츠크',
    'RB Leipzig': 'RB 라이프치히',
    'SK Sturm Graz': '슈투름 그라츠',
    'FK Crvena Zvezda': '츠르베나 즈베즈다',
    'BSC Young Boys': '영 보이즈',
    'FC Red Bull Salzburg': '레드불 잘츠부르크',
    'ŠK Slovan Bratislava': '브라티슬라바'
}

export const championsPlayerName: TranslatedKoreanVer = {
    'Harry Kane': '해리 케인',
    'Raphinha': '하피냐',
    'Jamie Bynoe-Gittens': '제이미 기튼스',
    'Sehrou Guirassy': '세루 기라시',
    'Florian Wirtz': '플로리안 비르츠',
    'Muhammed Kerem Aktürkoğlu': '케렘 아크튀르크올루',
    'Abdallah Sima': '압달라 시마',
    'Benjamin Šeško': '베냐민 세슈코',
    'Erling Haaland': '엘링 홀란드',
    'Karim Adeyemi': '카림 아데예미',
}