export const competitionName: Record<string, string> = {
    'PL': '프리미어리그',
    'BL1': '독일 분데스리가',
    'PD': '라리가',
    'SA': '세리에 A',
    'FL1': '리그 1',
    'CL': 'UEFA 챔피언스리그',
    'FCWC': 'FIFA 클럽 월드컵',
    'EL': 'UEFA 유로파리그',
    'UCL': 'UEFA 컨퍼런스 리그',
    'DFB': 'DFB 포칼',
    "CIT": '코파 이탈리아',
    'PPL': '프리메이라 리가',
    'TDL': '타사 다 리가',
    "DED": "에레디비시",
    "BJL": "벨기에 프로 리그",
    "CB": "크로키 컵",
    "UPL": "우크라이나 프리미어리그",
    "SSL": "스위스 슈퍼 리그",
    "ABL": "오스트리아 분데스리가",
    "SPL": "스코티시 프리미어십"
}