type TranslatedKoreanVer = Record<string, string>;

export const nationality: TranslatedKoreanVer = {
    "Norway": "노르웨이",
    "Nigeria": "나이지리아",
    "England": "잉글랜드",
    "Cameroon": "카메룬",
    "Spain": "스페인",
    "France": "프랑스",
    "Sweden": "스웨덴",
    "Denmark": "덴마크",
    "Germany": "독일",
    "Guinea": "기니",
    "Belgium": "벨기에",
    "Czech Republic": "체코",
    "DR Congo": "콩고민주공화국",
    "Brazil": "브라질",
    "Netherlands": "네덜란드",
    "Venezuela": "베네수엘라",
    "Uruguay": "우루과이",
    "Argentina": "아르헨티나",
    "Morocco": "모로코",
    "Italy": "이탈리아",
    "Serbia": "세르비아",
    "USA": "미국",
    "Egypt": "이집트",
    "Jordan": "요르단",
    "Japan": "일본",
    "Portugal": "포르투갈",
    "Colombia": "콜롬비아",
    "New Zealand": "뉴질랜드",
    "Senegal": "세네갈",
    "Bosnia-Herzegovina": "보스니아-헤르체고비나",
    "Croatia": "크로아티아",
    "Poland": "폴란드",
    "Georgia": "조지아",
    "Romania": "루마니아",
    "Canada": "캐나다",
    "South Korea": "대한민국",
    "Slovenia": "슬로베니아",
    "Turkey": "튀르키예",
    "Australia": "호주",
    "Wales": "웨일스",
    "Austria": "오스트리아",
    "Northern Ireland": "북아일랜드",
    "Scotland": "스코틀랜드",
    "Switzerland": "스위스",
    "Chile": "칠레",
    "Slovakia": "슬로바키아",
    "Hungary": "헝가리",
    "Greece": "그리스",
    "Ireland": "아일랜드",
    "Russia": "러시아",
    "Albania": "알바니아",
    "Ghana": "가나",
    "Jamaica": "자메이카",
    "Finland": "핀란드",
    "Ukraine": "우크라이나",
    "Ecuador": "에콰도르",
    "Gambia": "감비아",
    "Paraguay": "파라과이",
    "Ivory Coast": "코트디부아르",
    "Iceland": "아이슬란드",
    "Mexico": "멕시코",
    "Burkina Faso": "부르키나파소",
    "Zambia": "잠비아",
    "Mali": "말리",
    "Kosovo": "코소보",
    "Iraq": "이라크",
    "Algeria": "알제리",
    "Gabon": "가봉",
    "Israel": "이스라엘",
    "North Macedonia": "북마케도니아",
    "Togo": "토고",
    "Montenegro": "몬테네그로",
    "Guadeloupe": "과달루프",
    "Tunisia": "튀니지",
    "Syria": "시리아",
    "Luxembourg": "룩셈부르크",
    "Armenia": "아르메니아",
    "Benin": "베냉",
    "Estonia": "에스토니아",
    "Costa Rica": "코스타리카",
    "Philippines": "필리핀",
    "Andorra": "안도라",
    "Cape Verde Islands": "카보베르데",
    "Mozambique": "모잠비크",
    "Cyprus": "키프로스",
    "Suriname": "수리남",
    "Peru": "페루",
    "Equatorial Guinea": "적도 기니",
    "Sierra Leone": "시에라리온",
    "Iran": "이란",
    "Zimbabwe": "짐바브웨",
    "Angola": "앙골라",
    "Lithuania": "리투아니아",
    "Saudi Arabia": "사우디아라비아",
    "Uzbekistan": "우즈베키스탄",
    "Bulgaria": "불가리아",
    "Congo": "콩고 공화국",
    "Indonesia": "인도네시아",
    "Panama": "파나마",
    "Central African Republic": "중앙아프리카공화국",
    "Kenya": "케냐",
    "Malta": "몰타",
    "Burundi": "부룬디",
    "Martinique": "마르티니크",
    "Guinea-Bissau": "기니비사우",
    "French Guiana": "프랑스령 기아나",
    "Madagascar": "마다가스카르",
    "Haiti": "아이티",
    "UA Emirates": "아랍에미리트",
    "Honduras": "온두라스"
}