type TranslatedKoreanVer = Record<string, string>;

export const nationality: TranslatedKoreanVer = {
    "Norway": "노르웨이",
    "Nigeria": "나이지리아",
    "England": "잉글랜드",
    "Cameroon": "카메룬",
    "Spain": "스페인",
    "France": "프랑스",
    "Sweden": "스웨덴",
    "Denmark": "덴마크",
    "Germany": "독일",
    "Guinea": "기니",
    "Belgium": "벨기에",
    "Czech Republic": "체코",
    "DR Congo": "콩고민주공화국",
    "Brazil": "브라질",
    "Netherlands": "네덜란드",
    "Venezuela": "베네수엘라",
    "Uruguay": "우루과이",
    "Argentina": "아르헨티나",
    "Morocco": "모로코",
    "Italy": "이탈리아",
    "Serbia": "세르비아",
    "USA": "미국",
    "Egypt": "이집트",
    "Jordan": "요르단",
    "Japan": "일본",
    "Portugal": "포르투갈",
    "Colombia": "콜롬비아",
    "New Zealand": "뉴질랜드",
    "Senegal": "세네갈",
    "Bosnia-Herzegovina": "보스니아-헤르체고비나",
    "Croatia": "크로아티아",
    "Poland": "폴란드",
    "Georgia": "조지아",
    "Romania": "루마니아",
    "Canada": "캐나다",
    "South Korea": "대한민국",
    "Slovenia": "슬로베니아",
    "Turkey": "튀르키예"
}