type TranslatedKoreanVer = Record<string, string>;

export const shortTeamName: TranslatedKoreanVer = {
    // 프리미어리그
    "Man City": "맨시티",
    "West Ham": "웨스트햄",
    "Tottenham": "토트넘",
    "Liverpool": "리버풀",
    "Arsenal": "아스날",
    "Brighton Hove": "브라이튼",
    "Aston Villa": "아스톤 빌라",
    "Man United": "맨유",
    "Brentford": "브렌트포드",
    "Chelsea": "첼시",
    "Crystal Palace": "C.팰리스",
    "Fulham": "풀럼",
    "Newcastle": "뉴캐슬",
    "Nottingham": "노팅엄",
    "Wolverhampton": "울버햄튼",
    "Bournemouth": "본머스",
    "Ipswich Town": "입스위치",
    "Leicester City": "레스터",
    "Southampton": "사우스햄튼",
    "Everton": "에버튼",

    // 분데스리가
    "Union Berlin": "우니온 베를린",
    "Bayern": "바이에른 뮌헨",
    "Leverkusen": "레버쿠젠",
    "Wolfsburg": "볼프스부르크",
    "Freiburg": "프라이부르크",
    "Dortmund": "도르트문트",
    "Frankfurt": "프랑크푸르트",
    "RB Leipzig": "라이프치히",
    "Stuttgart": "슈투트가르트",
    "Hoffenheim": "호펜하임",
    "Augsburg": "아우크스부르크",
    "M'gladbach": "묀헨글라트바흐",
    "Mainz": "마인츠",
    "Bochum": "보훔",
    "Holstein Kiel": "홀슈타인 킬",
    "Heidenheim": "하이덴하임",
    "St. Pauli": "장크트파울리",
    "Bremen": "베르더 브레멘",

    // 라리가
    "Real Madrid": "레알 마드리드",
    "Atleti": "AT 마드리드",
    "Girona": "지로나",
    "Barça": "바르셀로나",
    "Athletic": "아틀레틱 클루브",
    "Osasuna": "오사수나",
    "Valencia": "발렌시아",
    "Rayo Vallecano": "라요 바예카노",
    "Real Betis": "레알 베티스",
    "Valladolid": "바야돌리드",
    "Getafe": "헤타페",
    "Real Sociedad": "레알 소시에다드",
    "Villarreal": "비야레알",
    "Alavés": "D.알라베스",
    "Espanyol": "에스파뇰",
    "Las Palmas": "라스팔마스",
    "Mallorca": "마요르카",
    "Celta": "셀타 비고",
    "Leganés": "레가네스",
    "Sevilla FC": "세비야",

    // 세리에A
    "Milan": "AC 밀란",
    "Napoli": "나폴리",
    "Inter": "인터 밀란",
    "Verona": "엘라스 베로나",
    "Fiorentina": "피오렌티나",
    "Juventus": "유벤투스",
    "Lecce": "레체",
    "Atalanta": "아탈란타",
    "Monza": "몬차",
    "Venezia FC": "베네치아",
    "Genoa": "제노아",
    "Como": "코모",
    "Roma": "AS 로마",
    "Bologna": "볼로냐",
    "Cagliari": "칼리아리",
    "Torino": "토리노",
    "Udinese": "우디세네",
    "Lazio": "라치오",
    "Empoli": "엠폴리",
    "Parma": "파르마",

    // 리그1
    "Monaco": "AS 모나코",
    "Marseille": "마르세유",
    "Stade de Reims": "스타드 드 랭스",
    "Brest": "브레스투아",
    "Strasbourg": "스트라스부르",
    "Stade Rennais": "스타드 렌",
    "Angers SCO": "앙제",
    "PSG": "PSG",
    "Montpellier": "몽펠리에",
    "Lille": "릴",
    "Toulouse": "툴루즈",
    "Saint-Étienne": "생테티엔",
    "Nice": "니스",
    "Le Havre": "르아브르",
    "Nantes": "낭트",
    "RC Lens": "랑스",
    "Olympique Lyon": "리옹",
    "Auxerre": "오세르",

    // 챔피언스리그
    "Sporting CP": "스포르팅",
    "SL Benfica": "벤피카",
    "Feyenoord": "페예노르트",
    "Celtic": "셀틱",
    "Sparta Praha": "S.프라하",
    "Dinamo Zagreb": "D.자그레브",
    "Club Brugge": "브뤼헤",
    "PSV": "PSV",
    "Shaktar": "샤흐타르",
    "Sturm Graz": "슈투름 그라츠",
    "Crvena Zvedza": "즈베즈다",
    "Young Boys": "영 보이즈",
    "RB Salzburg": "잘츠부르크",
    "Sl. Bratislava": "브라티슬라바"
}