type TranslatedKoreanVer = Record<string, string>;

export const shortTeamName: TranslatedKoreanVer = {
    // 프리미어리그
    "Man City": "맨시티",
    "West Ham": "웨스트햄",
    "Tottenham": "토트넘",
    "Liverpool": "리버풀",
    "Arsenal": "아스날",
    "Brighton Hove": "브라이튼",
    "Aston Villa": "아스톤 빌라",
    "Man United": "맨유",
    "Brentford": "브렌트포드",
    "Chelsea": "첼시",
    "Crystal Palace": "C.팰리스",
    "Fulham": "풀럼",
    "Newcastle": "뉴캐슬",
    "Nottingham": "노팅엄",
    "Wolverhampton": "울버햄튼",
    "Bournemouth": "본머스",
    "Ipswich Town": "입스위치",
    "Leicester City": "레스터",
    "Southampton": "사우스햄튼",
    "Everton": "에버튼",

    // 분데스리가
    "Union Berlin": "우니온 베를린",
    "Bayern": "바이에른 뮌헨",
    "Leverkusen": "레버쿠젠",
    "Wolfsburg": "볼프스부르크",
    "Freiburg": "프라이부르크",
    "Dortmund": "도르트문트",
    "Frankfurt": "프랑크푸르트",
    "RB Leipzig": "라이프치히",
    "Stuttgart": "슈투트가르트",
    "Hoffenheim": "호펜하임",
    "Augsburg": "아우크스부르크",
    "M'gladbach": "묀헨글라트바흐",
    "Mainz": "마인츠",
    "Bochum": "보훔",
    "Holstein Kiel": "홀슈타인 킬",
    "Heidenheim": "하이덴하임",
    "St. Pauli": "장크트파울리",
    "Bremen": "베르더 브레멘",

    // 라리가
    "Real Madrid": "레알 마드리드",
    "Atleti": "AT 마드리드",
    "Girona": "지로나",
    "Barça": "바르셀로나",
    "Athletic": "아틀레틱 클루브",
    "Osasuna": "오사수나",
    "Valencia": "발렌시아",
    "Rayo Vallecano": "라요 바예카노",
    "Real Betis": "레알 베티스",
    "Valladolid": "바야돌리드",
    "Getafe": "헤타페",
    "Real Sociedad": "레알 소시에다드",
    "Villarreal": "비야레알",
    "Deportivo": "데포르티보 알라베스",
    "Espanyol": "에스파뇰",
    "Las Palmas": "라스팔마스",
    "Mallorca": "마요르카",
    "Celta": "셀타 비고",
    "Leganés": "레가네스",
    "Sevilla FC": "세비야"
}