type TranslatedKoreanVer = Record<string, string>;

export const plTeamsName: TranslatedKoreanVer = {
    "Manchester City FC": "맨체스터 시티",
    "West Ham United FC": "웨스트햄 유나이티드",
    "Tottenham Hotspur FC": "토트넘 홋스퍼",
    "Liverpool FC": "리버풀",
    "Arsenal FC": "아스날",
    "Brighton & Hove Albion FC": "브라이튼 앤 호브 알비온",
    "Aston Villa FC": "아스톤 빌라",
    "Manchester United FC": "맨체스터 유나이티드",
    "Brentford FC": "브렌트포드",
    "Chelsea FC": "첼시",
    "Crystal Palace FC": "크리스탈 팰리스",
    "Fulham FC": "풀럼",
    "Newcastle United FC": "뉴캐슬 유나이티드",
    "Nottingham Forest FC": "노팅엄 포레스트",
    "Wolverhampton Wanderers FC": "울버햄튼 원더러스",
    "AFC Bournemouth": "본머스",
    "Ipswich Town FC": "입스위치 타운",
    "Leicester City FC": "레스터 시티",
    "Southampton FC": "사우스햄튼",
    "Everton FC": "에버튼"
}

export const bundesTeamName: TranslatedKoreanVer = {
    "1. FC Union Berlin": "우니온 베를린",
    "FC Bayern München": "바이에른 뮌헨",
    "Bayer 04 Leverkusen": "바이엘 04 레버쿠젠",
    "VfL Wolfsburg": "볼프스부르크",
    "SC Freiburg": "프라이부르크",
    "Borussia Dortmund": "보루시아 도르트문트",
    "Eintracht Frankfurt": "프랑크푸르트",
    "RB Leipzig": "RB 라이프치히",
    "VfB Stuttgart": "슈투트가르트",
    "TSG 1899 Hoffenheim": "호펜하임",
    "FC Augsburg": "아우크스부르크",
    "Borussia Mönchengladbach": "보루시아 묀헨글라트바흐",
    "1. FSV Mainz 05": "FSV 마인츠 05",
    "VfL Bochum 1848": "VFL 보훔",
    "Holstein Kiel": "홀슈타인 킬",
    "1. FC Heidenheim 1846": "하이덴하임",
    "FC St. Pauli 1910": "FC 장크트파울리",
    "SV Werder Bremen": "베르더 브레멘",
}

export const laligaTeamName: TranslatedKoreanVer = {
    "Real Madrid CF": "레알 마드리드",
    "Club Atlético de Madrid": "아틀레티코 마드리드",
    "Girona FC": "지로나",
    "FC Barcelona": "FC 바르셀로나",
    "Athletic Club": "아틀레틱 클럽 빌바오",
    "CA Osasuna": "오사수나",
    "Valencia CF": "발렌시아 CF",
    "Rayo Vallecano de Madrid": "라요 바예카노",
    "Real Betis Balompié": "레알 베티스",
    "Real Valladolid CF": "레알 바야돌리드",
    "Getafe CF": "헤타페",
    "Real Sociedad de Fútbol": "레알 소시에다드",
    "Villarreal CF": "비야레알",
    "Deportivo Alavés": "데포르티보 알라베스",
    "RCD Espanyol de Barcelona": "RCD 에스파뇰",
    "UD Las Palmas": "UD 라스팔마스",
    "RCD Mallorca": "RCD 마요르카",
    "RC Celta de Vigo": "셀타 비고",
    "CD Leganés": "CD 레가네스",
    "Sevilla FC": "세비야"
}

export const serieTeamName: TranslatedKoreanVer = {
    "AC Milan": "AC 밀란",
    "SSC Napoli": "SSC 나폴리",
    "FC Internazionale Milano": "인터 밀란",
    "Hellas Verona FC": "엘라스 베로나",
    "ACF Fiorentina": "피오렌티나",
    "Juventus FC": "유벤투스",
    "US Lecce": "US 레체",
    "Atalanta BC": "아탈란타",
    "AC Monza": "AC 몬차",
    "Venezia FC": "베네치아",
    "Genoa CFC": "제노아",
    "Como 1907": "코모",
    "AS Roma": "AS 로마",
    "Bologna FC 1909": "볼로냐",
    "Cagliari Calcio": "칼리아리 칼초",
    "Torino FC": "토리노",
    "Udinese Calcio": "우디세네 칼초",
    "SS Lazio": "SS 라치오",
    "Empoli FC": "엠폴리",
    "Parma Calcio 1913": "파르마 칼초"
}

export const leagueTeamName: TranslatedKoreanVer = {
    "AS Monaco FC": "AS 모나코",
    "Olympique de Marseille": "올림피크 마르세유",
    "Stade de Reims": "스타드 드 랭스",
    "Stade Brestois 29": "스타드 브레스투아",
    "RC Strasbourg Alsace": "RC 스트라스부르",
    "Stade Rennais FC 1901": "스타드 렌",
    "Angers SCO": "앙제 OSC",
    "Paris Saint-Germain FC": "파리 생제르맹",
    "Montpellier HSC": "몽펠리에 HSC",
    "Lille OSC": "OSC 릴",
    "Toulouse FC": "툴루즈",
    "AS Saint-Étienne": "AS 생테티엔",
    "OGC Nice": "OGC 니스",
    "Le Havre AC": "르아브르",
    "FC Nantes": "FC 낭트",
    "Racing Club de Lens": "RC 랑스",
    "Olympique Lyonnais": "올림피크 리옹",
    "AJ Auxerre": "AJ 오세르"
}

export const championsTeamName: TranslatedKoreanVer = {
    'Aston Villa FC': "아스톤 빌라",
    'Liverpool FC': '리버풀',
    'Manchester City FC': '맨체스터 시티',
    'AS Monaco FC': 'AS 모나코',
    'Stade Brestois 29': '스타드 브레스투아',
    'Bayer 04 Leverkusen': '바이엘 04 레버쿠젠',
    'FC Internazionale Milano': '인터 밀란',
    'Sporting Clube de Portugal': '스포르팅',
    'Arsenal FC': '아스날',
    'FC Barcelona': '바르셀로나',
    'Borussia Dortmund': '보루시아 도르트문트',
    'Real Madrid CF': '레알 마드리드',
    'Sport Lisboa e Benfica': 'SL 벤피카',
    'Juventus FC': '유벤투스',
    'Lille OSC': 'OSC 릴',
    'Feyenoord Rotterdam': '페예노르트',
    'Atalanta BC': '아탈란타',
    'VfB Stuttgart': '슈투트가르트',
    'Paris Saint-Germain FC': '파리 생제르맹',
    'Celtic FC': '셀틱',
    'AC Sparta Praha': '스파르타 프라하',
    'GNK Dinamo Zagreb': '디나모 자그레브',
    'FC Bayern München': '바이에른 뮌헨',
    'Girona FC': '지로나',
    'AC Milan': 'AC 밀란',
    'Club Brugge KV': '브뤼헤',
    'Club Atlético de Madrid': '아틀레티코 마드리드',
    'PSV': 'PSV 에인트호번',
    'Bologna FC 1909': '볼로냐',
    'FK Shakhtar Donetsk': '샤흐타르 도네츠크',
    'RB Leipzig': 'RB 라이프치히',
    'SK Sturm Graz': '슈투름 그라츠',
    'FK Crvena Zvezda': '츠르베나 즈베즈다',
    'BSC Young Boys': '영 보이즈',
    'FC Red Bull Salzburg': '레드불 잘츠부르크',
    'ŠK Slovan Bratislava': '브라티슬라바'
}
